name: PR

on:
    pull_request:
        branches:
            - main

jobs:
    yugioh-spring:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Java
                uses: actions/setup-java@v3
                with:
                    distribution: "temurin"
                    java-version: "11"
                    check-latest: true
                    cache: "gradle"

            -   name: Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: apps:yugioh-spring:clean apps:yugioh-spring:build --parallel
