spring:
  application:
    name: spring-vertx
  profiles:
    active: ide
server:
  servlet:
    context-path: /${spring.application.name}

---

spring:
  config:
    activate:
      on-profile: ide
  redis:
    host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
core:
  domain: localhost
  port: 8888
