### Java status endpoint
GET http://localhost:8080/java/api/v1.0/status

### Kotlin status endpoint
GET http://localhost:8080/kotlin/api/v1.0/status

### Join Games
POST http://localhost:8080/java/api/v1.0/games/vvv1

### Join Games
POST http://localhost:8080/java/api/v1.0/games/vvv2