### Java status endpoint
GET http://localhost:8080/java/api/v1.0/status

> {%
client.test("Request executed successfully", function() {
    client.log(client.global.get("bearerTokenV").toString());
    client.log(client.global.get("bearerTokenQ").toString());
    client.log(client.global.get("bearerTokenM").toString());
    client.log(client.global.get("uuid").toString());
  client.assert(response.status === 200, "Response status is not 200");
});
%}


### Vincent Login
POST http://localhost:8080/java/api/v1.0/auth:login
Content-Type: application/json

{
  "username": "vincent",
  "password": "123456"
}

> {% client.global.set("bearerTokenV", response.headers.valueOf("Authorization")); %}


### qrtt1 Login
POST http://localhost:8080/java/api/v1.0/auth:login
Content-Type: application/json

{
  "username": "qrtt1",
  "password": "123456"
}

> {% client.global.set("bearerTokenQ", response.headers.valueOf("Authorization")); %}


### Musk Login
POST http://localhost:8080/java/api/v1.0/auth:login
Content-Type: application/json

{
  "username": "musk",
  "password": "123456"
}

> {% client.global.set("bearerTokenM", response.headers.valueOf("Authorization")); %}


### Vincent Join Games
POST http://localhost:8080/java/api/v1.0/duelField:join
Authorization: Bearer {{bearerTokenV}}

> {% client.global.set("uuid", response.body.duelFieldUuid.toString()); %}


### qrtt1 Join Games
POST http://localhost:8080/java/api/v1.0/duelField:join
Authorization: Bearer {{bearerTokenQ}}


### Vincent Get DuelField By Uuid (Duelist)
GET http://localhost:8080/java/api/v1.0/duelField/{{uuid}}
Authorization: Bearer {{bearerTokenV}}


### Musk Get DuelField By Uuid
GET http://localhost:8080/java/api/v1.0/duelField/{{uuid}}
Authorization: Bearer {{bearerTokenM}}


### Vincent Draw Card
POST http://localhost:8080/java/api/v1.0/duelField/{{uuid}}/LEFT:drawCard
Authorization: Bearer {{bearerTokenV}}


### Vincent Summon Monster
POST http://localhost:8080/java/api/v1.0/duelField/{{uuid}}/LEFT:summonMonster
Authorization: Bearer {{bearerTokenV}}
Content-Type: application/json

{
  "uuid": "d0f01132-9ad7-4e5c-bae1-a067e18fbbf9"
}


### Vincent Apply Spell
POST http://localhost:8080/java/api/v1.0/duelField/{{uuid}}/LEFT:applySpell?skip=true
Authorization: Bearer {{bearerTokenV}}
Content-Type: application/json

{
  "uuid": "860481ab-1cdd-4539-8910-b5c80b92a2e6"
}


### Vincent Cover Trap
POST http://localhost:8080/java/api/v1.0/duelField/{{uuid}}/LEFT:coverTrap
Authorization: Bearer {{bearerTokenV}}
Content-Type: application/json

{
  "uuid": "99dff81d-a922-4346-b806-6339304c3c61",
  "state": "BACK"
}

### Vincent Start Battle
POST http://localhost:8080/java/api/v1.0/duelField/{{uuid}}/LEFT:startBattle
Authorization: Bearer {{bearerTokenV}}
Content-Type: application/json

{
  "uuid": "5ba31681-6ce6-4805-9dd7-98c778dd63b8"
}


### qrtt1 Draw Card
POST http://localhost:8080/java/api/v1.0/duelField/{{uuid}}/RIGHT:drawCard
Authorization: Bearer {{bearerTokenQ}}


### qrtt1 Summon Monster
POST http://localhost:8080/java/api/v1.0/duelField/{{uuid}}/RIGHT:summonMonster
Authorization: Bearer {{bearerTokenQ}}
Content-Type: application/json

{
  "uuid": "65178d75-ba3a-4f3f-806e-318b6b2a72ac"
}


### qrtt1 Apply Spell
POST http://localhost:8080/java/api/v1.0/duelField/{{uuid}}/RIGHT:applySpell
Authorization: Bearer {{bearerTokenQ}}
Content-Type: application/json

{
  "uuid": "94ab5d8d-a763-459e-88d2-c5e8e44a7a51"
}


### qrtt1 Cover Trap
POST http://localhost:8080/java/api/v1.0/duelField/{{uuid}}/RIGHT:coverTrap
Authorization: Bearer {{bearerTokenQ}}
Content-Type: application/json

{
  "uuid": "86d54dda-777f-4243-b842-dfa430f5a535",
  "state": "BACK"
}

### qrtt1 Start Battle
POST http://localhost:8080/java/api/v1.0/duelField/{{uuid}}/RIGHT:startBattle?skip=true
Authorization: Bearer {{bearerTokenQ}}
Content-Type: application/json

{
  "uuid": "9c67000f-feac-4024-ad7a-632ac89d9fa0"
}
