# nonk8s
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: yugioh
build:
  artifacts:
    - image: docker.io/hhnj/yugioh
      context: .
      jib:
        project: framework
        type: gradle
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  kubectl: {}
