spring:
    application:
        name: yugioh
    profiles:
        active: ide
server:
    servlet:
        context-path: /${spring.application.name}
springdoc:
    swagger-ui:
        doc-expansion: none

---

spring:
    config:
        activate:
            on-profile: ide

---

spring:
    config:
        activate:
            on-profile: stage
